2023-10-26 08:55:18,852 - process_api - ERROR - Message: unknown error: Failed to create Chrome process.
Stacktrace:
	GetHandleVerifier [0x00007FF6BFE88EF2+54786]
	(No symbol) [0x00007FF6BFDF5612]
	(No symbol) [0x00007FF6BFCAA64B]
	(No symbol) [0x00007FF6BFCD7586]
	(No symbol) [0x00007FF6BFCD53BE]
	(No symbol) [0x00007FF6BFD13FBB]
	(No symbol) [0x00007FF6BFD13A30]
	(No symbol) [0x00007FF6BFD0BC43]
	(No symbol) [0x00007FF6BFCE0941]
	(No symbol) [0x00007FF6BFCE1B84]
	GetHandleVerifier [0x00007FF6C01D7F52+3524194]
	GetHandleVerifier [0x00007FF6C022D800+3874576]
	GetHandleVerifier [0x00007FF6C0225D7F+3843215]
	GetHandleVerifier [0x00007FF6BFF25086+694166]
	(No symbol) [0x00007FF6BFE00A88]
	(No symbol) [0x00007FF6BFDFCA94]
	(No symbol) [0x00007FF6BFDFCBC2]
	(No symbol) [0x00007FF6BFDECC83]
	BaseThreadInitThunk [0x00007FFD3C64257D+29]
	RtlUserThreadStart [0x00007FFD3D3AAA78+40]

2023-10-26 08:55:18,868 - process_api - ERROR - Traceback (most recent call last):
  File "C:\Development\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\Development\PragmaDev\ui_testing_service\process_api\process_runner.py", line 27, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\Development\PragmaDev\ui_testing_service\process_api\modules\selenium\__init__.py", line 19, in init_driver
    driver = await DriverActions.init(browser, options)
  File "C:\Development\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\driver.py", line 14, in init
    driver = await browser_fn(options)
  File "C:\Development\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\driver.py", line 43, in chrome
    driver = webdriver.Chrome(service=chrome_service, options=opt)
  File "C:\Development\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Development\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Development\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "C:\Development\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Development\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "C:\Development\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Failed to create Chrome process.
Stacktrace:
	GetHandleVerifier [0x00007FF6BFE88EF2+54786]
	(No symbol) [0x00007FF6BFDF5612]
	(No symbol) [0x00007FF6BFCAA64B]
	(No symbol) [0x00007FF6BFCD7586]
	(No symbol) [0x00007FF6BFCD53BE]
	(No symbol) [0x00007FF6BFD13FBB]
	(No symbol) [0x00007FF6BFD13A30]
	(No symbol) [0x00007FF6BFD0BC43]
	(No symbol) [0x00007FF6BFCE0941]
	(No symbol) [0x00007FF6BFCE1B84]
	GetHandleVerifier [0x00007FF6C01D7F52+3524194]
	GetHandleVerifier [0x00007FF6C022D800+3874576]
	GetHandleVerifier [0x00007FF6C0225D7F+3843215]
	GetHandleVerifier [0x00007FF6BFF25086+694166]
	(No symbol) [0x00007FF6BFE00A88]
	(No symbol) [0x00007FF6BFDFCA94]
	(No symbol) [0x00007FF6BFDFCBC2]
	(No symbol) [0x00007FF6BFDECC83]
	BaseThreadInitThunk [0x00007FFD3C64257D+29]
	RtlUserThreadStart [0x00007FFD3D3AAA78+40]


2023-10-26 08:55:25,702 - process_api - INFO - Task 762ad8dd-a5b9-4994-b58d-f823d60b36fa completed in 00:00:07:588
