2023-10-26 11:42:16,258 - process_api - INFO - run schema: "file attachments"
2023-10-26 11:42:16,258 - process_api - INFO - run process: "main"
2023-10-26 11:42:16,258 - process_api - INFO - run step: "start"
2023-10-26 11:42:16,265 - process_api - ERROR - Message: invalid argument
  (Session info: chrome=118.0.5993.70)
Stacktrace:
	GetHandleVerifier [0x00007FF6BFE88EF2+54786]
	(No symbol) [0x00007FF6BFDF5612]
	(No symbol) [0x00007FF6BFCAA4FD]
	(No symbol) [0x00007FF6BFC99139]
	(No symbol) [0x00007FF6BFC974DD]
	(No symbol) [0x00007FF6BFC97CA3]
	(No symbol) [0x00007FF6BFCACA5F]
	(No symbol) [0x00007FF6BFD25077]
	(No symbol) [0x00007FF6BFD0BE6A]
	(No symbol) [0x00007FF6BFD24D02]
	(No symbol) [0x00007FF6BFD0BC43]
	(No symbol) [0x00007FF6BFCE0941]
	(No symbol) [0x00007FF6BFCE1B84]
	GetHandleVerifier [0x00007FF6C01D7F52+3524194]
	GetHandleVerifier [0x00007FF6C022D800+3874576]
	GetHandleVerifier [0x00007FF6C0225D7F+3843215]
	GetHandleVerifier [0x00007FF6BFF25086+694166]
	(No symbol) [0x00007FF6BFE00A88]
	(No symbol) [0x00007FF6BFDFCA94]
	(No symbol) [0x00007FF6BFDFCBC2]
	(No symbol) [0x00007FF6BFDECC83]
	BaseThreadInitThunk [0x00007FFD3C64257D+29]
	RtlUserThreadStart [0x00007FFD3D3AAA78+40]

2023-10-26 11:42:16,270 - process_api - ERROR - Traceback (most recent call last):
  File "C:\Development\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\Development\PragmaDev\ui_testing_service\process_api\process_runner.py", line 27, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\Development\PragmaDev\ui_testing_service\process_api\modules\selenium\__init__.py", line 37, in goto
    await goto(selenium_driver, url)
  File "C:\Development\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\navigate.py", line 2, in goto
    driver.get(url)
  File "C:\Development\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 353, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Development\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "C:\Development\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=118.0.5993.70)
Stacktrace:
	GetHandleVerifier [0x00007FF6BFE88EF2+54786]
	(No symbol) [0x00007FF6BFDF5612]
	(No symbol) [0x00007FF6BFCAA4FD]
	(No symbol) [0x00007FF6BFC99139]
	(No symbol) [0x00007FF6BFC974DD]
	(No symbol) [0x00007FF6BFC97CA3]
	(No symbol) [0x00007FF6BFCACA5F]
	(No symbol) [0x00007FF6BFD25077]
	(No symbol) [0x00007FF6BFD0BE6A]
	(No symbol) [0x00007FF6BFD24D02]
	(No symbol) [0x00007FF6BFD0BC43]
	(No symbol) [0x00007FF6BFCE0941]
	(No symbol) [0x00007FF6BFCE1B84]
	GetHandleVerifier [0x00007FF6C01D7F52+3524194]
	GetHandleVerifier [0x00007FF6C022D800+3874576]
	GetHandleVerifier [0x00007FF6C0225D7F+3843215]
	GetHandleVerifier [0x00007FF6BFF25086+694166]
	(No symbol) [0x00007FF6BFE00A88]
	(No symbol) [0x00007FF6BFDFCA94]
	(No symbol) [0x00007FF6BFDFCBC2]
	(No symbol) [0x00007FF6BFDECC83]
	BaseThreadInitThunk [0x00007FFD3C64257D+29]
	RtlUserThreadStart [0x00007FFD3D3AAA78+40]


2023-10-26 11:42:21,721 - process_api - INFO - Task 448987ea-b00c-4281-80c8-9fd8e8f0a7f5 completed in 00:00:03:372
